language: node_js
sudo: false
node_js:
- 4
- 6
- 8
- 10
install:
- npm run setup
script:
- npm run lint
- npm test
after_success:
- npm run deploy
env:
  global:
  - FIREBASE_API_KEY=AIzaSyDmDqVttwfQwBDTfl3frWl3oMaBez6Wuu8
  - FIREBASE_PROJECT_ID=moltres-test
  - FIREBASE_MESSAGING_SENDER_ID=524696319278
  - secure: O/e/cljvQ241GZYmhRfiYTlcDPB3eLKUeksuFVIwCbJOY6h/v6MzUGeQCSdmSULrtPqUu+OBBwOfNUM85QV/k+j+DyVhTZJZPlnYkDggKDQfru/ci/8fKGvmyEjRW0fmH/JXJktUELAxw+I7gGEfmcgxfiGrG42txROBkdcROv4W17k/HlACPnKeJ+W4G7qyo76SJHkw7vKJ31vh3y4ANr/QYPsELejhvUXt/lBuK3oTzu7AWE9a8RJBNeD8+oW884eJ4SrkksrU0ltmf0yENbohC0Kl4fNMWlD7rCkc19NbI2SGgdL2rHLB2z+/sZVuNsz1tTckJ8/BDpj8YUaJSUQqoye0BSTsjxIidKxqwR1cqNrbR8FrqUIfQTzfBNy1SaOufZZ1J1e2A5Q6awu3SjBAjICaHYU/EYv2kg3MqhYmcP0Dc58uTTpmKxZqGoSTU9DP2Za9M08Fa/myqVYwQOZdw8ThPrwVh060cbcJE7JappAGpWZpGBVz8mtf7+Kaae2009p7o/IWyKCVpA4TsItM2KkmoSKMvMp94JJo1SeDezh8m9soDQWCPPweLDCMttdOhbZY8RqeeY01kXUApEMz7DbsUaWwnhcnrlMypPVu/4LJgXv6JVajD994tLgU525QjFX15Se48CIKzl9ksZiOvHZH2XMOw6JE92xeZiY=
  - secure: Clpb+7zCddhAGYqat6UhhlbMuBekpgmPOYEDGzKt6PK4vxLd9B1u2IKl9MNqc27EAkK2DGm7hlyjxFyhP12R+r0awtv7DWyOit4NrQg8dtvdDQIQ5mz9HlE5rWSrydw9/yH+TfbxKPpr5KrZjMiE2z2ZND7kMkRTQeIcyLJa7d+KtJ9HE6Ug6jV6Mez9+QyMa4NM0f82SCIqb23x1dWeTq4+pVM9+iwmwgindldTdVziez9MdImhxTNEd1+Y0K0YxtqWzW6if84hhr3OY+tGVDjm6jnEl1Fpm+U64P1gbQbakpdRYEPocXDhNBN97a5Bw6KhIFZckG3mGDGdI52T+a3Fdd3s9u45gSJGYPtkaenzNvxQYL+k4sYHyUEtVr82qWppB6zB6M0StcfhS+nWotdhOC/cZvEVgpqQLv25W9ccBOeuhDjWxqonJQMhQ1XGiXdQSZp9pmrZzKwsikKWlSb2gNMd9n1Ic7Kb7E4JKOfFR9BR12DxZMf+TZhc+06ynS7Jx02PlkCPSgRIPBN/XE5+ogeBB3g6R+kf+mzv7FeMg1juRxH3BxrEG7JbvRILbSRoc61PpWsHfamDpO7M81X4tw8LCaH6jhCNzdQwYO02Pz4XuvTJBKxFMcqrivFLQWd9HWzdCX7tw+APr1NFiwoP7Mg2oy4bGSvxorIjZrg=
