language: node_js
sudo: required
addons:
  apt:
    update: true
node_js:
- 6
- 8
- 10
before_install:
- npm run setup:ci
install:
- npm run setup
script:
- npm run lint
- npm run test:ci
after_success:
- npm run deploy
env:
  global:
  - FIREBASE_API_KEY=AIzaSyDmDqVttwfQwBDTfl3frWl3oMaBez6Wuu8
  - FIREBASE_PROJECT_ID=moltres-test
  - FIREBASE_MESSAGING_SENDER_ID=524696319278
  - secure: MZwMv19yDkRDgZ5QeaR05xguOKBGfB3P+fVgyQ2thbFSXPtm9ctDsQfd43qFrTVuIdQl3CEPAyb7YCpVMgp/sLJYTreheneNVL7MnEEIjKb+KmL+v0KiAta+IB3wHvn0Qwp5DaTlHfedbJYCqulY1Ezwr+notC6K+OFyTZyjgGkkhuDSYxHrSyFOoQi12H2bC9z+KUrJQCuBigtBGVWNBgp1+pqndHJTzJEjTzzp2G0BJSUacyGg3BigeCO4OiQDufqKRPlGgkGOCvje+zBIGc7p9mBhE84sjkSmJRHdBsykHSpLUxarkMQ+g0w4wzcnRSuKtgEehEf3XfV41saP9Oka+QNOX5uZTJ1t6IXJzSIzEgJjQ2UHkL/MoltUy3w+tlVzHDH3TbFvpeSfL/aC0lANZbzt7OlqakXxTU9W4f9OpXMENz7u2dM+5723h2TR/I0lNKQNw5GeS/jG7IPtgMFPLPBCjEAV2xgOOBpSXlRb2P+LL5AzKCeWgkkgiLj3/n6nQ0dLVeMH/tvGVEVLqITcCWxQX/Pyrjll7upJiCy2lYQGde8p0b2jP1p8KEK6QkoHzuxZ7tXYC1Ozeo3IpqbrNRgJ78uDH3RRefLc2HIHvy6NhA/IHVId77XeYsaN8xk790pXYBPBmS3DNQDhJt1nTgSmfG/orkH96Rmvqsg=
  - secure: EHoPjs1VJcoNKid3sOWxkjRR5tZ+y6F9NtuxM7wsNen3ynsl2ZWcM0ESUWns9dt6esWGelhdiznB5J9Csr36LFI/+y4QhnaAuYLYnvm4THSLKCEmNioU785VBIdjkZ4Fvh39+P/KvGDLehLuCrebU2cxXsSVMj0yUwC9JMNMLqFtZ84GMG6GIbGMiouz902QL57uayjDuvUqIpWiG04cGuJAeEY9raFpoyj1eS4BFqJOzxuSy9i6HM7AmMjgS0H7EY0zREH3MtUx6f7l5WwBId++ffOLxgjV8DOBHiG5fu3wEgln69Q/NghKn8WykwVRln7at4AwXmu2gutBDBCfmU6rkpUk/Y9Dvde9B66tWWuIP56BCLnTcNBChtJEmikiL8+DCs6dfsbPZ2iqH1cm9mSbGyN/vK3GCcAWYH4CRkB6RGaFyyxwHDjp4Dsve3piytFYxJtUvaMMaqLSUqXFZBs4IgwDHdfqgbceA88GlgmFDXX8xY5MQhBGGNRhfEYvtf2IragdS40EePb4JnRgEcJbpSQUEkh5nM06vt8EaP3Ao4GYD/N7LCiIRB/kDTkiEuI5M1DPq6MgT33IlzaGpuHLtjMIwWunxJzYrYTAp0MMUY8GX3wCiiBAkPKVsIF1m5oQw4fhwfyY9kAsessol6glLvhfw6Bbl8Acr4vY2k8=
